theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = false
true-color = true
bufferline = "always"
# rulers = [80]

[editor.soft-wrap]
enable = true
wrap-at-text-width = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.space]

[keys.normal.f]
f = "file_picker"

[keys.normal]
# a hack to utilize lf as file tree picker
# C-e = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme base16_transparent"]
# C-e = [":new", ":pipe lf-pick"]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"
q = ":quit"
"?" = "command_palette"
X = "extend_line_above"
G = "goto_file_end"

[keys.normal.g]
c = "toggle_comments"

[keys.normal.";"]
";" = ":write"
k = "half_page_up"
j = "half_page_down"
K = "page_up"
J = "page_down"

