theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.space]

[keys.normal]
q = ":quit"
"?" = "command_palette"
X = "extend_line_above"
G = "goto_file_end"

[keys.normal.g]
c = "toggle_comments"

[keys.normal.";"]
";" = ":write"
k = "half_page_up"
j = "half_page_down"
K = "page_up"
J = "page_down"

