import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
  # - ./kanagawa/dragon.yml

env:
  TERM: xterm-256color

font:
  size: 14
  normal:
    family: "cascadia code"
  bold:
    family: "cascadia code"
  italic:
    family: "cascadia code"

window:
  opacity: 0.95
  padding:
    x: 10
    y: 10
